### ISSUE TITLE
Обновление фильтров

### ISSUE THREAD

**Issue by vladd** [arrer/WarframeAgent#34]
Необходимо время от времени перечитывать фильтры с сайта и обновлять их. Соответственно, на время обновления нужно заблокировать работу системы фильтров (или перечитать фильтры из памяти).

Открытые вопросы:
* Периодичность обновления?
* Адрес, с которого нужно обновляться?
* Что делать, если свежепрочитанные фильтры невозможно распарсить? (Только логировать?)

**Comment by EvgeniyZ-ru-zz** [comment]
- Фильтры обновляются на самом GitHub редко, но если появится что то, то сразу должно быть у пользователей. Значит берез примерно тоже время, что и обновление данных минута-две.
- Есть [API](https://evgeniy-z.ru/api/v2/agent/filters/url), которое дает ссылки для нужных фильтров. Можно использовать прямую загрузку с GitHub, а можно через API брать ссылку и только потом грузить фильтр. Но я думаю фильтры так и останутся на GitHub, поэтому прямая загрузка вполне подойдет. Также URL есть в файле настроек самого приложения.
- Использовать старый. Выводить лог. По сути, если ошибка в чтение JSON файла будет, то программа даже не сможет узнать версию фильтра, а это значит, что она дальше не полезет.

**Comment by vladd** [comment]
По идее, с фильтрами всё? Закрываем таск.

**Comment by vladd** [comment]
Хм, тогда переоткроем. Сейчас есть обновление данных при обновлении `Item`'ов, но не остальных фильтров.
